@echo off
echo Stopping all PM2 processes...
call pm2 delete all

echo Starting test server...
call pm2 start ecosystem.config.js

echo Waiting for server to start...
timeout /t 5

echo Checking PM2 status...
call pm2 list

echo Testing server...
curl http://localhost:3000

echo Checking logs...
call pm2 logs