#!/bin/bash
#############################################
# Database Security Hardening Script
# Purpose: Secure PostgreSQL/MySQL for Strapi
# Run as: sudo bash 18-database-security.sh
#############################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${YELLOW}========================================${NC}"
echo -e "${YELLOW}  Database Security Hardening${NC}"
echo -e "${YELLOW}========================================${NC}"
echo ""

# Check root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: Run as root: sudo bash $0${NC}"
    exit 1
fi

# Detect database type
POSTGRES_INSTALLED=false
MYSQL_INSTALLED=false

if command -v psql &> /dev/null; then
    POSTGRES_INSTALLED=true
    echo -e "${GREEN}✓ PostgreSQL detected${NC}"
fi

if command -v mysql &> /dev/null; then
    MYSQL_INSTALLED=true
    echo -e "${GREEN}✓ MySQL/MariaDB detected${NC}"
fi

if [ "$POSTGRES_INSTALLED" = false ] && [ "$MYSQL_INSTALLED" = false ]; then
    echo -e "${YELLOW}No database detected. Skipping database-specific hardening.${NC}"
    echo "This script supports PostgreSQL and MySQL/MariaDB."
    exit 0
fi

# Step 1: PostgreSQL hardening
if [ "$POSTGRES_INSTALLED" = true ]; then
    echo ""
    echo -e "${BLUE}[PostgreSQL] Applying security hardening...${NC}"
    
    # Find PostgreSQL config directory
    PG_VERSION=$(psql --version | grep -oP '\d+' | head -1)
    PG_CONF="/etc/postgresql/${PG_VERSION}/main/postgresql.conf"
    PG_HBA="/etc/postgresql/${PG_VERSION}/main/pg_hba.conf"
    
    if [ -f "$PG_CONF" ]; then
        # Backup configs
        cp "$PG_CONF" "${PG_CONF}.backup.$(date +%Y%m%d)"
        cp "$PG_HBA" "${PG_HBA}.backup.$(date +%Y%m%d)"
        
        echo -e "${BLUE}Applying PostgreSQL security settings...${NC}"
        
        # Create security configuration
        cat > /etc/postgresql/${PG_VERSION}/main/conf.d/security.conf << 'PGCONF'
# PostgreSQL Security Configuration
# Generated by MaasISO security hardening

# Connection Security
listen_addresses = 'localhost'          # Only local connections
port = 5432
max_connections = 100

# SSL Configuration (enable if needed)
# ssl = on
# ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
# ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'

# Authentication
password_encryption = scram-sha-256     # Strongest password encryption

# Logging for security auditing
log_connections = on
log_disconnections = on
log_statement = 'ddl'                    # Log schema changes
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

# Prevent privilege escalation
log_min_error_statement = error

# Resource limits
statement_timeout = 60000               # 60 seconds max query time
idle_in_transaction_session_timeout = 300000  # 5 minutes

# Row Security
row_security = on
PGCONF

        # Ensure pg_hba.conf is secure
        cat > "$PG_HBA" << 'PGHBA'
# PostgreSQL Client Authentication Configuration
# 
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             postgres                                peer
local   all             all                                     peer

# IPv4 local connections (password required)
host    all             all             127.0.0.1/32            scram-sha-256

# IPv6 local connections (password required)  
host    all             all             ::1/128                 scram-sha-256

# Reject all other connections
host    all             all             0.0.0.0/0               reject
PGHBA

        # Restart PostgreSQL
        systemctl restart postgresql
        
        echo -e "${GREEN}✓ PostgreSQL hardened${NC}"
    else
        echo -e "${YELLOW}PostgreSQL config not found at expected location${NC}"
    fi
fi

# Step 2: MySQL/MariaDB hardening
if [ "$MYSQL_INSTALLED" = true ]; then
    echo ""
    echo -e "${BLUE}[MySQL/MariaDB] Applying security hardening...${NC}"
    
    # Create security configuration
    cat > /etc/mysql/conf.d/security.cnf << 'MYSQLCONF'
# MySQL Security Configuration
# Generated by MaasISO security hardening

[mysqld]
# Bind to localhost only
bind-address = 127.0.0.1

# Disable remote root login
# (handled separately)

# Disable LOAD DATA LOCAL
local-infile = 0

# Disable symbolic links
symbolic-links = 0

# Secure file permissions
secure-file-priv = /var/lib/mysql-files

# Log queries for auditing
general_log = 0
general_log_file = /var/log/mysql/mysql.log

# Log slow queries
slow_query_log = 1
slow_query_log_file = /var/log/mysql/mysql-slow.log
long_query_time = 2

# Connection limits
max_connections = 100
max_connect_errors = 10

# Password policy (if validate_password plugin available)
# validate_password.length = 12
# validate_password.policy = STRONG
MYSQLCONF

    # Run mysql_secure_installation equivalent
    echo -e "${YELLOW}Running MySQL security fixes...${NC}"
    
    mysql -e "DELETE FROM mysql.user WHERE User='';" 2>/dev/null || true
    mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');" 2>/dev/null || true
    mysql -e "DROP DATABASE IF EXISTS test;" 2>/dev/null || true
    mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';" 2>/dev/null || true
    mysql -e "FLUSH PRIVILEGES;" 2>/dev/null || true
    
    systemctl restart mysql 2>/dev/null || systemctl restart mariadb 2>/dev/null || true
    
    echo -e "${GREEN}✓ MySQL/MariaDB hardened${NC}"
fi

# Step 3: Create database user audit script
echo ""
echo -e "${BLUE}[3/4] Creating database audit tools...${NC}"

cat > /usr/local/bin/db-security-audit << 'EOF'
#!/bin/bash
#############################################
# Database Security Audit
#############################################

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=========================================="
echo "Database Security Audit"
echo "=========================================="
echo ""

# PostgreSQL audit
if command -v psql &> /dev/null; then
    echo -e "${BLUE}=== PostgreSQL ===${NC}"
    
    echo "Users with superuser privileges:"
    sudo -u postgres psql -c "SELECT usename, usesuper FROM pg_user WHERE usesuper = true;" 2>/dev/null
    
    echo ""
    echo "Users that can create databases:"
    sudo -u postgres psql -c "SELECT usename, usecreatedb FROM pg_user WHERE usecreatedb = true;" 2>/dev/null
    
    echo ""
    echo "Connection settings:"
    sudo -u postgres psql -c "SHOW listen_addresses;" 2>/dev/null
    sudo -u postgres psql -c "SHOW password_encryption;" 2>/dev/null
    
    echo ""
    echo "Recent connections (if logged):"
    tail -20 /var/log/postgresql/*.log 2>/dev/null | grep -i "connection" || echo "No recent connection logs"
fi

# MySQL audit
if command -v mysql &> /dev/null; then
    echo ""
    echo -e "${BLUE}=== MySQL/MariaDB ===${NC}"
    
    echo "Users and hosts:"
    mysql -e "SELECT User, Host FROM mysql.user;" 2>/dev/null || echo "Cannot access mysql.user"
    
    echo ""
    echo "Users with GRANT option:"
    mysql -e "SELECT User, Host FROM mysql.user WHERE Grant_priv='Y';" 2>/dev/null
    
    echo ""
    echo "Bind address:"
    mysql -e "SHOW VARIABLES LIKE 'bind_address';" 2>/dev/null
fi

echo ""
echo -e "${GREEN}Audit complete${NC}"
EOF
chmod +x /usr/local/bin/db-security-audit

# Step 4: Create backup user with minimal privileges
echo ""
echo -e "${BLUE}[4/4] Creating secure backup user...${NC}"

if [ "$POSTGRES_INSTALLED" = true ]; then
    # Create read-only backup user for PostgreSQL
    sudo -u postgres psql << 'SQLEOF' 2>/dev/null || true
-- Create backup role with minimal privileges
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'backup_user') THEN
        CREATE ROLE backup_user WITH LOGIN PASSWORD 'CHANGE_THIS_PASSWORD';
    END IF;
END
$$;

-- Grant read-only access to all databases
GRANT CONNECT ON DATABASE postgres TO backup_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO backup_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO backup_user;
SQLEOF
    echo -e "${YELLOW}Note: Change backup_user password: ALTER USER backup_user PASSWORD 'newpass';${NC}"
fi

echo ""
echo -e "${YELLOW}========================================${NC}"
echo -e "${GREEN}  Database Security Hardening Complete!${NC}"
echo -e "${YELLOW}========================================${NC}"
echo ""
echo -e "${BLUE}Applied settings:${NC}"
echo "  ✓ Database bound to localhost only"
echo "  ✓ Strong password encryption"
echo "  ✓ Connection logging enabled"
echo "  ✓ Anonymous users removed"
echo "  ✓ Remote root access disabled"
echo ""
echo -e "${BLUE}Commands:${NC}"
echo "  db-security-audit  - Run security audit"
echo ""
echo -e "${YELLOW}Important:${NC}"
echo "  1. Change default database passwords"
echo "  2. Create application-specific users with minimal privileges"
echo "  3. Regularly review database access logs"