import React from 'react'

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: any
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
