name: Deploy to VPS2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Debug SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "Setting up SSH key..."
          echo "${{ secrets.VPS2_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          echo "Setting up known_hosts..."
          echo "${{ secrets.VPS2_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          echo "Setting permissions..."
          chmod 600 ~/.ssh/deploy_key
          chmod 600 ~/.ssh/known_hosts
          echo "Checking files..."
          ls -la ~/.ssh/
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -v root@147.93.62.188 'echo "SSH connection successful"'
          
      - name: Deploy to VPS2
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p 22" \
            .next/ \
            public/ \
            package.json \
            package-lock.json \
            next.config.js \
            root@147.93.62.188:/var/www/jouw-frontend-website/
            
      - name: Restart PM2 service
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p 22 root@147.93.62.188 '
            cd /var/www/jouw-frontend-website && 
            npm ci --production && 
            pm2 restart frontend || pm2 start npm --name "frontend" -- start
          '
          
      - name: Verify Deployment
        run: |
          # Wait for service to start
          sleep 10
          # Check health endpoint
          curl --fail http://147.93.62.188/api/health || exit 1
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "Deployment failed. Starting rollback..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p 22 root@147.93.62.188 '
            cd /var/www/jouw-frontend-website && 
            if [ -d "backup" ]; then
              rm -rf .next public package.json package-lock.json next.config.js && 
              cp -r backup/* . && 
              npm ci --production && 
              pm2 restart frontend
            fi
          '